import customOption from '../customOption';
import hooks from '../../hooks/login/SignupBusinessHooksField';
export default {
  fields: {
    email: {
      type: 'email',
      name: 'email',
      placeholder: '아이디 (이메일)',
      label: '아이디 (이메일)',
      rules: 'required|email|string|between:5,25',
      hooks,
    },
    emailButton: {
      label: '중복 확인',
    },
    password: {
      type: 'password',
      name: 'password',
      placeholder: '비밀번호',
      label: '비밀번호',
      rules:
        'required|string|regex:/^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,15}$/',
      hooks,
    },
    passwordConfirm: {
      type: 'password',
      name: 'passwordConfirm',
      placeholder: '비밀번호 확인',
      label: '비밀번호 확인',
      autoComplete: 'passwordConfirm',
      rules: 'required|string|same:password',
      hooks,
    },
    profilePhoto: {
      type: 'file',
      label: '프로필 사진',
      hooks,
    },
    companyRegistrationNumber: {
      type: 'text',
      name: 'companyRegistrationNumber',
      placeholder: '사업자등록번호',
      value: '',
      label: '사업자 등록번호',
      rules: 'required|string',
      hooks,
    },
    corporationRegistrationNumber: {
      type: 'text',
      name: 'corporationRegistrationNumber',
      placeholder: '법인 등록번호',
      value: '',
      label: '법인 등록번호',
      hooks,
    },
    companyName: {
      type: 'text',
      name: 'companyName',
      placeholder: '상호명',
      label: '상호명',
      rules: 'required|string',
      hooks,
    },
    businessDivision: {
      extra: customOption.companyDivision,
      placeholder: '사업자 구분',
      rules: 'required',
      hooks,
    },
    representativeName: {
      type: 'text',
      name: 'representativeName',
      placeholder: '대표 이름',
      label: '대표 이름',
      rules: 'required|string',
      hooks,
    },
    mobile: {
      type: 'tel',
      name: 'mobile',
      placeholder: '대표 전화번호',
      label: '대표 전화번호',
      rules: 'required|string|between:12,13',
      value: '',
      hooks,
    },
    mobileButton: {
      label: '본인인증',
    },
    authMobile: {
      type: 'number',
      name: 'authMobile',
      label: '',
      placeholder: '인증번호',
      value: '',
      hooks,
    },
    authMobileButton: { label: '인증' },
    authMobileCountdown: {},
    addressViewButton: {
      label: '주소 찾기',
    },
    addressView: {
      type: 'text',
      name: 'AddressView',
      placeholder: '사업자 주소 (우편번호)',
      label: '사업자 주소 (우편번호)',
      hooks,
    },
    addressViewButton: {
      label: '주소 찾기',
    },
    roadAddress: {},
    address: {},
    zip: {},
    detailAddress: {
      type: 'text',
      name: 'companyDetailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },

    businessType: {
      type: 'text',
      name: 'businessType',
      placeholder: '업태',
      label: '업태',
      rules: 'required|string',
      hooks,
    },
    businessItem: {
      type: 'text',
      name: 'businessItem',
      placeholder: '종목',
      label: '종목',
      rules: 'required|string',
      hooks,
    },
    businessRegistration: {
      type: 'file',
      label: '사업자 등록증 사본',
    },
    certificateSeal: {
      type: 'file',
      label: '대표자 인감증명서 사본 (발급일 3개월 이내)',
    },
    entityRegistrationCertificate: {
      type: 'file',
      label: '법인등기사항전부증명서 사본',
    },
    representativeBankCopy: {
      type: 'file',
      label: '대표자 명의 통장 사본 등록',
    },
    mailorderRegistration: {
      type: 'file',
      label: '통신판매업신고증 사본',
    },

    mailorderBusiness: {
      label: '통신판매업 신고하셨습니까?',
      extra: customOption.mailorderBusiness,
    },
    mailorderRegistrationNumber: {
      type: 'number',
      type: 'text',
      name: 'mailorderRegistrationNumber',
      label: '통신 판매업 신고 번호',
      placeholder: '통신 판매업 신고 번호',
      value: '',
      hooks,
    },
    notReportingTypeSelect: {
      extra: customOption.businessMailOrderReason,
      placeholder: '미신고 유형',
      hooks,
    },
    notReportingType: {
      type: 'text',
      name: 'notReportingType',
      label: '기타',
      placeholder: '기타 (텍스트 입력)',
      rules: 'string',
      hooks,
    },
    managerSameAsUser: {
      type: 'checkbox',
      name: 'managerSameAsUser',
      label: '사업자 정보 동일',
      rules: 'boolean|accepted',
      hooks,
    },
    managerName: {
      type: 'text',
      name: 'managerName',
      label: '담당자 성명',
      placeholder: '담당자 성명',
      rules: 'required|string',
      hooks,
    },
    managerEmail: {
      type: 'email',
      name: 'managerEmail',
      placeholder: '이메일',
      label: '이메일',
      rules: 'required|string',
      hooks,
    },
    managerMobile: {
      type: 'tel',
      name: 'managerMobile',
      placeholder: '휴대폰 번호',
      label: '휴대폰 번호',
      rules: 'required|string|between:12,13',
      value: '',
      hooks,
    },
    managerTelephone: {
      type: 'tel',
      name: 'managerTelephone',
      placeholder: '유선 번호(선택)',
      value: '',
      hooks,
    },
    fax: {
      type: 'tel',
      name: 'fax',
      placeholder: '팩스 번호(선택)',
      value: '',
      hooks,
    },

    calculationReceivingMethod: {
      name: 'calculationReceivingMethod',
      label: '정산대금 수신 방법',
      default: 'SALES_DEPOSIT',
      value: 'SALES_DEPOSIT',
      extra: customOption.calculationReceivingMethod,
    },
    bankCode: {
      extra: customOption.bank,
      placeholder: '은행명 선택',
      rules: 'required',
      hooks,
    },
    accountNumber: {
      type: 'tel',
      name: 'accountNumber',
      placeholder: '계좌번호',
      value: '',
      label: '계좌번호',
      rules: 'required|string',
      hooks,
    },
    accountHolder: {
      type: 'text',
      name: 'accountHolder',
      placeholder: '예금주명',
      label: '예금주명',
      rules: 'required|string',
      hooks,
    },
    accountHolderButton: {
      label: '계좌 확인',
    },
    originSameAsUser: {
      type: 'checkbox',
      name: 'originSameAsUser',
      label: '판매자 정보 동일',
      value: false,
      hooks,
    },
    departureName: {
      type: 'text',
      name: 'departureName',
      placeholder: '출고지명',
      label: '출고지명',
      rules: 'required|string',
      hooks,
    },
    departureTelephone: {
      type: 'tel',
      name: 'departureTelephone',
      placeholder: '출고지 전화번호',
      label: '출고지 전화번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    departureAddressView: {
      type: 'text',
      name: 'departureAddressView',
      placeholder: '출고지 주소 (우편번호)',
      label: '출고지 주소 (우편번호)',
      hooks,
    },
    departureAddress: {},
    departureRoadAddress: {},
    departureZip: {},
    departureDetailAddress: {
      type: 'text',
      name: 'departureDetailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },
    returnSameAsUser: {
      type: 'checkbox',
      name: 'returnSameAsUser',
      label: '판매자 정보 동일',
      hooks,
    },
    returnName: {
      type: 'text',
      name: 'returnName',
      placeholder: '반품/교환지 명',
      label: '반품/교환지 명',
      rules: 'required|string',
      hooks,
    },
    returnTelephone: {
      type: 'tel',
      name: 'returnTelephone',
      placeholder: '반품/교환지 전화번호',
      label: '반품/교환지 전화번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    returnAddressView: {
      type: 'text',
      name: 'returnAddress',
      placeholder: '반품/교환지 주소(우편번호)',
      label: '반품/교환지 주소(우편번호)',
      hooks,
    },
    returnAddress: {},
    returnRoadAddress: {},
    returnDetailAddress: {
      type: 'text',
      name: 'returnDetailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },
    returnZip: {},
    storeName: {
      type: 'text',
      name: 'storeName',
      placeholder: '닉네임',
      label: '닉네임',
      rules: 'required|string|regex:/^[가-힣a-zA-Z0-9._]+$/',
      hooks,
    },
    storeButton: {
      label: '중복 확인',
    },
    claimTelephone: {
      type: 'tel',
      name: 'claimTelephone',
      placeholder: '고객응대 대표번호',
      label: '고객응대 대표번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    claimTelephoneButton: {
      type: 'checkbox',
      name: 'claimTelephoneButton',
      label: '담당자 동일',
      value: false,
      hooks,
    },
    storeIntroduction: {
      type: 'text',
      name: 'storeIntroduction',
      placeholder: '스토어 소개(선택)',
    },
    emailConfirm: {
      value: false,
    },
    authMobileConfirm: {
      value: false,
    },
    accountConfirm: {
      value: false,
    },
    storeConfirm: {
      value: false,
    },
  },
};
