import customOption from '../customOption';
import hooks from '../../hooks/login/SignupSellerHooksField';

export default {
  fields: {
    email: {
      type: 'email',
      name: 'email',
      label: '아이디 (이메일)',
      placeholder: '아이디 (이메일)',
      rules: 'required|email|string|between:5,25',
      hooks,
    },
    emailButton: {
      label: '중복 확인',
    },
    password: {
      type: 'password',
      name: 'password',
      label: '비밀번호',
      placeholder: '비밀번호',
      rules:
        'required|string|regex:/^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,15}$/',
      hooks,
    },
    passwordConfirm: {
      type: 'password',
      name: 'passwordConfirm',
      label: '비밀번호 확인',
      placeholder: '비밀번호 확인',
      autoComplete: 'passwordConfirm',
      rules: 'required|string|same:password',
      hooks,
    },
    profilePhoto: {
      type: 'file',
      label: '프로필 사진',
    },
    name: {
      type: 'text',
      name: 'name',
      label: '성명',
      placeholder: '성명',
      rules: 'required|string',
      hooks,
    },
    mobile: {
      type: 'tel',
      name: 'mobile',
      label: '전화번호',
      placeholder: '전화번호',
      value: '',
      rules: 'required|string|between:12,13',
      hooks,
    },
    mobileButton: {
      label: '본인인증',
    },
    authMobile: {
      type: 'number',
      name: 'authMobile',
      label: '',
      placeholder: '인증번호',
      value: '',
      hooks,
    },
    authMobileButton: { label: '인증' },
    authMobileCountdown: {},
    gender: {
      extra: customOption.gender,
      placeholder: '성별',
      rules: 'required',
      hooks,
    },
    birthYear: {
      extra: customOption.year,
      placeholder: '년도',
      rules: 'required',
      hooks,
    },
    birthMonth: {
      extra: customOption.month,
      placeholder: '월',
      rules: 'required',
      hooks,
    },
    birthDay: {
      extra: customOption.day,
      placeholder: '일',
      rules: 'required',
      hooks,
    },
    addressView: {
      type: 'text',
      name: 'addressView',
      placeholder: '주소(우편번호)',
      label: '주소(우편번호)',
      hooks,
    },
    addressViewButton: {
      label: '주소 찾기',
    },
    address: {},
    roadAddress: {},
    detailAddress: {
      type: 'text',
      name: 'detailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },
    zip: {},
    managerSameAsUser: {
      type: 'checkbox',
      name: 'managerSameAsUser',
      label: '판매자 정보 동일',
      value: false,
      hooks,
    },
    managerName: {
      type: 'text',
      name: 'managerName',
      placeholder: '담당자 성명',
      label: '담당자 성명',
      rules: 'required|string',
      hooks,
    },
    managerEmail: {
      type: 'email',
      name: 'managerEmail',
      placeholder: '이메일',
      label: '이메일',
      rules: 'required|string',
      hooks,
    },
    managerMobile: {
      type: 'tel',
      name: 'managerMobile',
      placeholder: '휴대폰 번호',
      value: '',
      label: '휴대폰 번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    managerTelephone: {
      type: 'tel',
      name: 'managerTelephone',
      placeholder: '유선 번호(선택)',
      value: '',
      rules: 'string|between:12,13',
      hooks,
    },
    fax: {
      type: 'tel',
      name: 'fax',
      placeholder: '팩스 번호(선택)',
      value: '',
      rules: 'string|between:12,13',
      hooks,
    },
    calculationReceivingMethod: {
      name: 'calculationReceivingMethod',
      label: '정산대금 수신 방법',
      default: 'SALES_DEPOSIT',
      value: 'SALES_DEPOSIT',
      extra: customOption.calculationReceivingMethod,
    },
    bankCode: {
      extra: customOption.bank,
      placeholder: '은행명 선택',
      rules: 'required',
      hooks,
    },
    accountNumber: {
      type: 'tel',
      name: 'accountNumber',
      placeholder: '계좌번호',
      value: '',
      label: '계좌번호',
      rules: 'required|string',
      hooks,
    },
    accountHolder: {
      type: 'text',
      name: 'accountHolder',
      placeholder: '예금주명',
      label: '예금주명',
      rules: 'required|string',
      hooks,
    },
    accountHolderButton: {
      label: '계좌 확인',
    },
    originSameAsUser: {
      type: 'checkbox',
      name: 'originSameAsUser',
      label: '판매자 정보 동일',
      value: false,
      hooks,
    },
    departureName: {
      type: 'text',
      name: 'departureName',
      placeholder: '출고지명',
      label: '출고지명',
      rules: 'required|string',
      hooks,
    },
    departureTelephone: {
      type: 'tel',
      name: 'departureTelephone',
      placeholder: '출고지 전화번호',
      label: '출고지 전화번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    departureAddressView: {
      type: 'text',
      name: 'departureAddressView',
      placeholder: '출고지 주소 (우편번호)',
      label: '출고지 주소 (우편번호)',
      hooks,
    },
    departureAddress: {},
    departureRoadAddress: {},
    departureZip: {},
    departureDetailAddress: {
      type: 'text',
      name: 'departureDetailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },
    returnSameAsUser: {
      type: 'checkbox',
      name: 'returnSameAsUser',
      label: '판매자 정보 동일',
      hooks,
    },
    returnName: {
      type: 'text',
      name: 'returnName',
      placeholder: '반품/교환지 명',
      label: '반품/교환지 명',
      rules: 'required|string',
      hooks,
    },
    returnTelephone: {
      type: 'tel',
      name: 'returnTelephone',
      placeholder: '반품/교환지 전화번호',
      label: '반품/교환지 전화번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    returnAddressView: {
      type: 'text',
      name: 'returnAddress',
      placeholder: '반품/교환지 주소(우편번호)',
      label: '반품/교환지 주소(우편번호)',
      hooks,
    },
    returnAddress: {},
    returnRoadAddress: {},
    returnDetailAddress: {
      type: 'text',
      name: 'returnDetailAddress',
      placeholder: '상세주소',
      label: '상세주소',
      rules: 'required|string',
      hooks,
    },
    returnZip: {},
    storeName: {
      type: 'text',
      name: 'storeName',
      placeholder: '닉네임',
      label: '닉네임',
      rules: 'required|string|regex:/^[가-힣a-zA-Z0-9._]+$/',
      hooks,
    },
    storeButton: {
      label: '중복 확인',
    },
    claimTelephone: {
      type: 'tel',
      name: 'claimTelephone',
      placeholder: '고객응대 대표번호',
      label: '고객응대 대표번호',
      rules: 'required|string|between:12,13',
      hooks,
    },
    claimTelephoneButton: {
      type: 'checkbox',
      name: 'claimTelephoneButton',
      label: '담당자 동일',
      value: false,
      hooks,
    },
    storeIntroduction: {
      type: 'text',
      name: 'storeIntroduction',
      placeholder: '스토어 소개(선택)',
    },
    emailConfirm: {
      value: false,
    },
    authMobileConfirm: {
      value: false,
    },
    accountConfirm: {
      value: false,
    },
    storeConfirm: {
      value: false,
    },
  },
};
