/**
 * search from enum
 */
const SearchEnum = {
    GLOBAL_SEARCH_INPUT: 'GLOBAL_SEARCH_INPUT',
    GLOBAL_SEARCH_RESULT: 'GLOBAL_SEARCH_RESULT',
    SELLER_STORE: 'SELLER_STORE',
    PROMOTION_PAGE: 'PROMOTION_PAGE',    

    DEFAULT_GLOBAL_SEARCH_UNIT_PER_PAGE : 20,
    DEFAULT_SELLER_STORE_UNIT_PER_PAGE : 24,
    DEFAULT_SEARCH_ORDER : 'DATE'
  };
  
export default SearchEnum;
  